name: ddev-dotcom-static
type: "nodejs:16"
web:
  locations:
    "/":
      root: ""
      index: ["index.html"]
      scripts: false
      allow: true
      expires: 24h
      rules:
        \.(css|js|gif|jpe?g|png|svg|webm)$:
          expires: 4w
  commands:
    start: sleep infinity
