# https://docs.platform.sh/define-routes/redirects.html

https://{default}/:
  type: upstream
  upstream: "ddev-dotcom-static:http"
  redirects:
    paths:
      "/ddev-local/ddev-wsl2-getting-started/":
        to: "https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/#windows-wsl2"
      "/ddev-local/apache-solr-with-drupal-8-and-search-api-solr/":
        to: "https://github.com/ddev/ddev-drupal9-solr"
      "/ddev-local/ddev-local-web-container-customization-in-v1-8-0/":
        to: "https://ddev.readthedocs.io/en/latest/users/extend/customizing-images/"
      "/ddev-local/ddev-local-nfs-mounting-setup-macos/":
        to: "https://ddev.readthedocs.io/en/latest/users/install/performance/#nfs"
      "/ddev-local":
        to: "https://ddev.com/blog"
      "/meet-the-team":
        to: "https://ddev.com/blog/authors"
      "/author/heather":
        to: "https://ddev.com/blog/author/heather-mcnamee"
      "/author/rfay":
        to: "https://ddev.com/blog/author/randy-fay"
      "/author/rmanelius":
        to: "https://ddev.com/blog/author/rick-manelius"
      "^/ddev-local/(.*)":
        to: "https://ddev.com/blog/$1"
        regexp: true
"https://www.{default}/":
  type: redirect
  to: "https://{default}/"
