# https://docs.platform.sh/define-routes/redirects.html

https://{default}/:
  redirects:
    paths:
      "^/ddev-local/(.*)":
        to: "https://ddev.com/blog/$1"
        regexp: true
      "/meet-the-team":
        to: "https://ddev.com/blog/authors"
      "/author/heather":
        to: "https://ddev.com/blog/author/heather-mcnamee"
      "/author/rfay":
        to: "https://ddev.com/blog/author/randy-fay"
      "/author/rmanelius":
        to: "https://ddev.com/blog/author/rick-manelius"
